services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: inventory_management_system
        ports:
            - "8080:80" # Apache exposed on http://localhost:8080
            - "5173:5173" # Vite dev server for HMR
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: inventory_management_system_db
        restart: always
        environment:
            MYSQL_DATABASE: inventory_db
            MYSQL_USER: alex
            MYSQL_PASSWORD: alex
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3355:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
